### PR TITLE
Translation basic information pt

### PR DESCRIPTION
**Pull request by sombo20**
- Portuguese is a Romance language originating from the Iberian Peninsula, widely spoken in Portugal, Brazil and several other nations. It is known for its regional diversity and rich history. "[Portuguese]"

# Team Debugers
Resolution the issue #85
@aosccode

Signed-off-by: sombo20 [vicentevictorsombo643@gmail.com](mailto:vicentevictorsombo643@gmail.com)

### CODE REVIEW

**Comment by antonio-pedro99** [comment]
@aosccode

**Comment by Busayo-ojo** [comment]
Hi @sombo20, thanks for working on this! Please can you properly sign this off so I can merge this pull request?

You can see this article for clarity on how to sign off your comits https://www.secondstate.io/articles/dco/

**Comment by aosccode** [comment]
@sombo20 Por favor, adicone sua assinatura no commit e não nos comentários :)

**Comment by antonio-pedro99** [comment]
@sombo20 are you signing this?

**Comment by sombo20** [comment]
@antonio-pedro99  I can't, I'm having problems

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 I can't, I'm having problems

To add your Signed-off-by line to every commit in this branch:

- Ensure you have a local copy of your branch by checking out the pull request locally via command line.
- In your local branch, run: git rebase HEAD~3 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin dev

**Comment by sombo20** [comment]
@antonio-pedro99 OK, I did all that, and then what should I do, should I wait to be verified or something?

**Comment by Busayo-ojo** [comment]
Hi @sombo20, can you properly sign this off so we can close this?
You can check this [article ](https://www.secondstate.io/articles/dco/)on how to properly sign off.

**Pull request merged**
