### PR TITLE
create new component-joinChaossAfrica, that sends message to newcomers

### PR DESCRIPTION
**Pull request by wendeee**
Hello, I've created the feature. Please, let me know if I need to make any changes. I await your feedback. Thank you.

### CODE REVIEW

**Review by misspee007 — COMMENTED** [review]
Thanks for the contribution! There's a couple of things to address though:

In joinChaossAfrica.js
- TEXT FORMATTING: I feel the text will look better with the following changes:
  - Adding newline characters at line 12 and 20. What I mean is:
  ```\nIn the meantime, you should check out our...``` 
  ```\nIf you have any questions...```
  
  - The way links work in the context of linking channels is this way:
  ```<#C03LUCA2988>``` instead of regular markdown syntax which is ```[#chaossafrica-cm for community managers](https://chaoss-workspace.slack.com/archives/C03LUCA2988)```
  - Mentioning people is similar. So on line 20, this ```[@Ruth Ikegah (She/her)](https://chaoss-workspace.slack.com/team/U0174P1MDAP) ```  should be ```<@U03D8A4SC8H>```

**Comment by misspee007** [comment]
Continuation... @wendeee 
- ERRORS:
  - ```The `text` argument is missing in the request payload for a chat.postMessage call - It's 
a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.```
If you check the other compnents, you will notice that there's always a text element just below the block. Adding this after line 25 will fix this bug:
```text: `Welcome to CHAOSS Africa! 🎉.` ```

  - ```bolt-app missing required field: channel```
In order to fix this, change ```channel: event.user.id``` on line 4, to ```channel: event.user```. To understand why, take a look at the [member_joined_channel](https://api.slack.com/events/member_joined_channel) event and notice what it returns. It's slightly different from the team_join event.
This brings us to the event handler in app.js. what you have is ```app.event('chaossafrica_join', async({ event, client, logger }) => {...}```. However, "chaossafrica_join" is **not** a valid event. You can see all the valid events at https://api.slack.com/events. What you should use in this case is "member_joined_channel".
Note: the ```member_joined_channel``` event affects all channels, so to make sure this callback only affects the chaoss-africa channel, go to joinChaossAfrica.js and add a conditional statement inside the try block, before the return statement. Like this:
```
try {
		if (event.channel !== "C03KC6ZERSR") {
			return;
		}

		return await client.chat.postMessage({....});
	}
```
"C03KC6ZERSR" is the channel ID for the chaoss-africa channel.

PS: Please test on your dev environment to catch any bugs before you make a pull request. you can test with channel ID and user ID's from your test workspace, but don't forget to change them back to the correct ID's before pushing. 

Thanks!

**Comment by misspee007** [comment]
One last thing @wendeee , your PR failed the DCO check because you did not sign-off your commits. Please read the [contribution guide](https://github.com/chaoss/chaoss-slack-bot/wiki/Contribution-Guide) if you're not sure what this means. To fix it, see https://www.secondstate.io/articles/dco/

**Comment by wendeee** [comment]
Thank you for the feedback. Will effect the corrections pointed out.

**Comment by wendeee** [comment]
I've implemented the corrections. However, I'm not exactly clear on how to test the changes from my end.

**Comment by misspee007** [comment]
Hello @wendeee, are you experiencing any challenges? Please let me know how I can help.

**Comment by wendeee** [comment]
I tested with this:
Screenshot (111)

And it gave me this:
Screenshot (110)

with no error on the console. 
But I don't know if I'm testing it the right way.

**Comment by wendeee** [comment]
The joinchaossAfrica function on line 100 is not executing. I think I'm doing something wrong.
Screenshot (113)

**Comment by wendeee** [comment]
Here is what the joinChaossAfrica component currently looks like:

Screenshot (114)

**Comment by misspee007** [comment]
> I tested with this: Screenshot (111)
> 
> And it gave me this: Screenshot (110)
> 
> with no error on the console. But I don't know if I'm testing it the right way.

That's because you can't access those chaoss channels from your test workspace. It would work fine in chaoss, but if you want to see it work in your test workspace, you have to replace the channel IDs with channels from your workspace.

**Comment by misspee007** [comment]
> Here is what the joinChaossAfrica component currently looks like:
> 
> Screenshot (114)

This isn't working for you because the if statement checks that the channel joined has an ID of "C03DKQ64WHE". If not, it returns and prevents the rest of the code from executing. This is to make sure the response is only triggered by joining the channel with that specific ID (which happens to be chaoss-africa channel).
So what you can do to test is replace this ID "C03DKQ64WHE" with the channel ID of the channel you want to test with. When you're done testing, remember to change it back.

**Comment by misspee007** [comment]
> The joinchaossAfrica function on line 100 is not executing. I think I'm doing something wrong. Screenshot (113)

Is there an error in the console?

**Comment by misspee007** [comment]
> Here is what the joinChaossAfrica component currently looks like:
> 
> Screenshot (114)

In the if block on line 4, make sure the ID in the double quotes is the ID of the channel you are testing with. let me know how that goes.

**Comment by misspee007** [comment]
> One last thing @wendeee , your PR failed the DCO check because you did not sign-off your commits. Please read the [contribution guide](https://github.com/chaoss/chaoss-slack-bot/wiki/Contribution-Guide) if you're not sure what this means. To fix it, see https://www.secondstate.io/articles/dco/
> 
> Let me know if you need anything!

To fix this one, click on "details" 
image
You will see something like this
image
Rebase the branch by running the commands on numbers 2 and 3.
To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> in every commit message. You can also do this automatically by using the -s flag (i.e., `git commit -s -m "your descriptive commit message"`)

**Comment by wendeee** [comment]
> > The joinchaossAfrica function on line 100 is not executing. I think I'm doing something wrong. Screenshot (113)
> 
> Is there an error in the console?

No, there is no error in the console.

**Comment by misspee007** [comment]
Looks great @wendeee, but you still need to fix that failed DCO check. I mentioned how to fix it in one of my previous comments. after that, we’re good to go 🕺🏽

**Comment by wendeee** [comment]
Hello👋, I've implemented the sign-off command. Thank you for the guide so far!  Let me know if there is any other addition I should make.

**Comment by misspee007** [comment]
Awesome! I'll merge now. Thank you so much for contributing.

**Pull request merged**
